pipeline {

    agent any

    environment {
        DOCKERHUB_CREDS = credentials('jenkins-homework')
        LC_ALL = "ru_RU.UTF-8"
        LANG    = "ru_RU.UTF-8"
        LANGUAGE = "ru_RU.UTF-8"
    }

    options {
        timestamps()
        skipDefaultCheckout(true)
	}

    stages {

        stage('Clone github repository') {
            steps {
                cleanWs()
                bat encoding: 'UTF-8', script: '''
                    chcp 65001
                    git clone -b main https://github.com/Pashtetickus/mle-lab-2.git'''
            }
        }

        stage('Checkout repo dir') {
            steps {
                bat encoding: 'UTF-8', script: '''
                                                chcp 65001
                                                cd mle-lab-2 && dir'''
            }
        }

        stage('Login'){
            steps {

                bat encoding: 'UTF-8', script: '''
                    chcp 65001
                    docker login -u %DOCKERHUB_CREDS_USR% -p %DOCKERHUB_CREDS_PSW%
                    '''
            }
        }
       
        stage('Create and run docker container') {
            steps {
                script {
                    try {
                        bat encoding: 'UTF-8', script: '''
                            chcp 65001
                            cd mle-lab-2 && docker-compose -f docker-compose-CI.yml build'''
                    }
                    finally {}
                }
            }
        }

        stage('Checkout container logs') {
            steps {
                dir("mle-lab-2") {
                        bat encoding: 'UTF-8', script: '''
                            chcp 65001
                            docker-compose -f docker-compose-CI.yml up -d
                            for /f %%i in ('docker ps -qf "name=^lab_2"') do set containerId=%%i
                            echo %containerId%
                            IF "%containerId%" == "" (
                                echo "No container running"
                            )
                            ELSE (
                                docker logs --tail 1000 -f %containerId%
                                )
                        '''
                    }
            }
        }

        stage('Checkout run report'){
            steps{
                dir("mle-lab-2"){
                    bat encoding: 'UTF-8', script: '''
                        chcp 65001
                        docker-compose logs -t --tail 10
                    '''
                }
            }
        }

        stage('Push'){
            steps{
                bat encoding: 'UTF-8', script: '''
                    chcp 65001
                    docker push pashtetick/mle-lab-2:latest'''
            }
        }

    }

    post {
        always {
            bat encoding: 'UTF-8', script: '''
                    chcp 65001
                    docker logout
                    '''
        }
    }

}